### ISSUE TITLE
Lua 5.3 with lua-struct

### ISSUE THREAD

**Issue by markuman** [moteus/ZipWriter#4]
When I replace the struct dependency (which fails to build with 5.3) with https://github.com/iryont/lua-struct, ZipWriter works fine with Lua 5.3 by now. 
What do you think about it?

**Comment by moteus** [comment]
On lua 5.3 it should use `string.pack`. I just do not know how create rockspec file.
https://github.com/moteus/ZipWriter/blob/master/lua/ZipWriter/binary_converter.lua#L4
\

**Comment by moteus** [comment]
Update readme.
So on Lua 5.3 you need only lzlib.
To install it you can use
```
luarocks install lzlib
luarocks install zipwriter --deps-mode=none
```
This is not best solution but I really have no idea how to write single rockspec file.
I do not like idea to support separate version of rockspec for each Lua version.
